apiVersion: v1
kind: ServiceAccount # Each pod associates with and able to set permissions for API server
metadata:
  name: elasticsearch-logging # Name of Service Account
  namespace: efklog # Associating this with specific 
  labels:
    k8s-app: elasticsearch-logging # label for identifuing the app in cluster
    addonmanager.kubernetes.io/mode: Reconcile # indicates resource should be managed by K8S
